'use strict';

// Protocol v3 (Noise handshake) tests — byte-level interop against fixtures
// generated by the Python reference stack (noiseprotocol, the engine
// poorman_handshake.noise wraps).  See test/generate_noise_vectors.py.
//
// The JS implementation acts as the Noise INITIATOR (node role) with the same
// fixed keys the fixtures were generated with, and must reproduce every
// handshake and transport byte the Python initiator produced, while decrypting
// everything the Python responder (server role) produced.

const { test, describe, before } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

// ── MockWebSocket (binary-capable) ────────────────────────────────────────────

let _lastMockWs = null;

class MockWebSocket {
    constructor(url) {
        this.url = url;
        this.sent = [];
        this.onopen = null;
        this.onmessage = null;
        this.onclose = null;
        this.binaryType = 'blob';
        this.closed = false;
        _lastMockWs = this;
    }
    send(data) { this.sent.push(data); }
    close() { this.closed = true; if (this.onclose) this.onclose(); }
    inject(data) {
        if (data instanceof ArrayBuffer) {
            if (this.onmessage) return this.onmessage({ data });
            return Promise.resolve();
        }
        const str = typeof data === 'string' ? data : JSON.stringify(data);
        if (this.onmessage) return this.onmessage({ data: str });
        return Promise.resolve();
    }
    triggerOpen() { if (this.onopen) this.onopen(); }
}

globalThis.WebSocket = MockWebSocket;

const {
    JarbasHiveMind, States,
    NoiseHandshake, NoiseTransport,
    selectNoiseOptions, buildNoisePrologue, canonicalJson,
    derivePskPBKDF2, derivePskArgon2, NOISE_SUITES_JS
} = require('../static/js/hivemind.js');

const vectors = JSON.parse(
    fs.readFileSync(path.join(__dirname, 'noise_vectors.json'), 'utf-8'));

function toHex(bytes) {
    return Array.from(bytes, b => b.toString(16).padStart(2, '0')).join('');
}
function fromHex(hex) {
    const arr = new Uint8Array(hex.length / 2);
    for (let i = 0; i < hex.length; i += 2) arr[i / 2] = parseInt(hex.slice(i, i + 2), 16);
    return arr;
}

// Web Crypto X25519 is required for protocol v3 (Node >= 20; Node 22 in CI).
// This is a hard requirement, not a silent skip: if unavailable, fail loudly.
let HAS_X25519 = false;
before(async () => {
    try {
        await crypto.subtle.generateKey({ name: 'X25519' }, false, ['deriveBits']);
        HAS_X25519 = true;
    } catch (_) { /* handled below */ }
});

describe('Web Crypto capability', () => {
    test('X25519 is available (required for protocol v3)', () => {
        assert.ok(HAS_X25519,
            'Web Crypto X25519 unavailable in this Node version — protocol v3 ' +
            'requires Node >= 20 with Secure Curves support');
    });
});

// ── Fixture-driven Noise handshake helpers ────────────────────────────────────

async function makeInitiator(v, pattern) {
    return await NoiseHandshake.create({
        pattern,
        suite: v.suite,
        psk: fromHex(v.psk_hex),
        prologue: fromHex(v.prologue_hex),
        staticPriv: fromHex(v.initiator_static_hex),
        ephemeralPriv: fromHex(v.initiator_ephemeral_hex),
        remoteStaticPub: pattern === 'KKpsk0'
            ? fromHex(v.responder_static_pub_hex) : undefined
    });
}

describe('Prologue construction (canonical JSON interop)', () => {
    test('buildNoisePrologue matches the Python reference bytes', () => {
        const v = vectors.xxpsk2;
        const prologue = buildNoisePrologue(
            v.hello_payload, v.handshake_payload, v.protocol_name);
        assert.equal(toHex(prologue), v.prologue_hex);
    });

    test('canonicalJson matches python json.dumps(sort_keys, compact)', () => {
        assert.equal(canonicalJson({ b: 1, a: [true, null, 'x'], c: { z: 2, y: 'ç' } }),
            '{"a":[true,null,"x"],"b":1,"c":{"y":"ç","z":2}}');
    });
});

for (const [suiteLabel, vkey] of [['ChaChaPoly', 'xxpsk2_chacha'], ['AESGCM', 'xxpsk2_aesgcm']])
describe('Noise_XXpsk2_' + suiteLabel + ' interop (Python responder fixtures)', () => {
    const v = vectors[vkey];

    test('full handshake reproduces the reference byte-for-byte', async () => {
        const hs = await makeInitiator(v, 'XXpsk2');

        // message 1: -> e  (payload: encodings + binarize, cleartext but hashed)
        const msg1 = await hs.writeMessage(new TextEncoder().encode(v.msg1_payload));
        assert.equal(toHex(msg1), v.msg1_hex, 'Noise message 1 must match');

        // message 2: <- e, ee, s, es, psk  (encrypted payload: server selection)
        const payload2 = await hs.readMessage(fromHex(v.msg2_hex));
        assert.equal(new TextDecoder().decode(payload2), v.msg2_payload);

        // message 3: -> s, se
        const msg3 = await hs.writeMessage(new Uint8Array(0));
        assert.equal(toHex(msg3), v.msg3_hex, 'Noise message 3 must match');

        assert.ok(hs.finished);
        assert.equal(toHex(hs.handshakeHash), v.handshake_hash_hex,
            'handshake hash (channel binding) must match');
        // remote static learned during the handshake (TOFU pinning material)
        assert.equal(toHex(hs.rs), v.responder_static_pub_hex);
    });

    test('transport: decrypts the Python server frame and reproduces the client frame', async () => {
        const hs = await makeInitiator(v, 'XXpsk2');
        await hs.writeMessage(new TextEncoder().encode(v.msg1_payload));
        await hs.readMessage(fromHex(v.msg2_hex));
        await hs.writeMessage(new Uint8Array(0));
        const transport = new NoiseTransport(hs);

        // server -> client (responder counter 0)
        const inner = await transport.decryptFrame(fromHex(v.server_transport_frame_hex));
        assert.equal(inner, v.server_transport_plaintext);

        // client -> server (initiator counter 0): AES-GCM with the Noise
        // counter nonce is deterministic, so the ciphertext must match exactly
        const frame = await transport.encryptFrame(v.client_transport_plaintext);
        assert.equal(toHex(frame), v.expected_client_transport_frame_hex);
    });

    test('replayed transport message is rejected (counter nonce)', async () => {
        const hs = await makeInitiator(v, 'XXpsk2');
        await hs.writeMessage(new TextEncoder().encode(v.msg1_payload));
        await hs.readMessage(fromHex(v.msg2_hex));
        await hs.writeMessage(new Uint8Array(0));
        const transport = new NoiseTransport(hs);

        await transport.decryptFrame(fromHex(v.server_transport_frame_hex));
        // same ciphertext again -> recv counter is now 1 -> AEAD failure
        await assert.rejects(
            () => transport.decryptFrame(fromHex(v.server_transport_frame_hex)));
    });

    test('wrong PSK fails cryptographically at handshake time', async () => {
        const hs = await makeInitiator(v, 'XXpsk2');
        await hs.writeMessage(new TextEncoder().encode(v.msg1_payload));
        // msg2 produced by a responder holding a different PSK
        await assert.rejects(() => hs.readMessage(fromHex(v.msg2_wrong_psk_hex)));
    });

    test('tampered prologue aborts the handshake (downgrade protection)', async () => {
        const tampered = buildNoisePrologue(
            v.hello_payload,
            Object.assign({}, v.handshake_payload, { max_protocol_version: 2 }),
            v.protocol_name);
        const hs = await NoiseHandshake.create({
            pattern: 'XXpsk2', suite: v.suite,
            psk: fromHex(v.psk_hex), prologue: tampered,
            staticPriv: fromHex(v.initiator_static_hex),
            ephemeralPriv: fromHex(v.initiator_ephemeral_hex)
        });
        await hs.writeMessage(new TextEncoder().encode(v.msg1_payload));
        await assert.rejects(() => hs.readMessage(fromHex(v.msg2_hex)));
    });
});

for (const [suiteLabel, vkey] of [['ChaChaPoly', 'kkpsk0_chacha'], ['AESGCM', 'kkpsk0_aesgcm']])
describe('Noise_KKpsk0_' + suiteLabel + ' interop (pre-provisioned static keys)', () => {
    const v = vectors[vkey];

    test('two-message handshake + transport round-trip match the reference', async () => {
        const hs = await makeInitiator(v, 'KKpsk0');

        const msg1 = await hs.writeMessage(new TextEncoder().encode(v.msg1_payload));
        assert.equal(toHex(msg1), v.msg1_hex, 'KK Noise message 1 must match');

        const payload2 = await hs.readMessage(fromHex(v.msg2_hex));
        assert.equal(new TextDecoder().decode(payload2), v.msg2_payload);
        assert.ok(hs.finished, 'KKpsk0 completes in two messages');
        assert.equal(toHex(hs.handshakeHash), v.handshake_hash_hex);

        const transport = new NoiseTransport(hs);
        const inner = await transport.decryptFrame(fromHex(v.server_transport_frame_hex));
        assert.equal(inner, v.server_transport_plaintext);
        const frame = await transport.encryptFrame(v.client_transport_plaintext);
        assert.equal(toHex(frame), v.expected_client_transport_frame_hex);
    });

    test('KKpsk0 requires the remote static public key', async () => {
        await assert.rejects(() => NoiseHandshake.create({
            pattern: 'KKpsk0', suite: v.suite,
            psk: fromHex(v.psk_hex), prologue: new Uint8Array(0)
        }), /remote static/);
    });
});

describe('PSK derivation', () => {
    test('derivePskArgon2 matches poorman derive_psk (argon2id, DEFAULT) byte-for-byte', async () => {
        const v = vectors.argon2id_psk;
        const psk = await derivePskArgon2(v.password, v.node_id);
        assert.equal(toHex(psk), v.expected_psk_hex);
        assert.equal(psk.length, 32);
    });
    test('derivePskPBKDF2 matches PBKDF2-HMAC-SHA256(password, SHA-256(node_id))', async () => {
        const v = vectors.pbkdf2_psk;
        const psk = await derivePskPBKDF2(v.password, v.node_id, v.iterations);
        assert.equal(toHex(psk), v.expected_psk_hex);
        assert.equal(psk.length, 32);
    });
});

describe('Negotiation (selectNoiseOptions)', () => {
    test('prefers the DEFAULT ChaChaPoly suite when both are offered', () => {
        const sel = selectNoiseOptions(['XXpsk2'],
            ['25519_AESGCM_SHA256', '25519_ChaChaPoly_SHA256'], null);
        assert.deepEqual(sel, { pattern: 'XXpsk2', suite: '25519_ChaChaPoly_SHA256' });
    });
    test('falls back to AESGCM when the server offers only AESGCM', () => {
        const sel = selectNoiseOptions(['XXpsk2'], ['25519_AESGCM_SHA256'], null);
        assert.deepEqual(sel, { pattern: 'XXpsk2', suite: '25519_AESGCM_SHA256' });
    });
    test('selects ChaChaPoly when the server offers only ChaChaPoly', () => {
        const sel = selectNoiseOptions(['XXpsk2'], ['25519_ChaChaPoly_SHA256'], null);
        assert.deepEqual(sel, { pattern: 'XXpsk2', suite: '25519_ChaChaPoly_SHA256' });
    });
    test('prefers KKpsk0 when a remote static key is pinned and offered', () => {
        const sel = selectNoiseOptions(['KKpsk0', 'XXpsk2'],
            ['25519_ChaChaPoly_SHA256'], 'aa'.repeat(32));
        assert.equal(sel.pattern, 'KKpsk0');
        assert.equal(sel.suite, '25519_ChaChaPoly_SHA256');
    });
    test('no mutual suite -> null', () => {
        assert.equal(selectNoiseOptions(['XXpsk2'], ['some_unknown_suite'], null), null);
    });
});

// ── Client-level protocol v3 integration (fixture replay) ────────────────────

describe('JarbasHiveMind protocol v3 client flow', () => {
    const v = vectors.xxpsk2;

    function connectV3(extraOptions) {
        const hm = new JarbasHiveMind();
        hm.connect('localhost', 5678, 'user', 'access-key', 'unused-password',
            Object.assign({
                psk: v.psk_hex,
                noiseStaticKey: v.initiator_static_hex,
                _noiseEphemeralKey: v.initiator_ephemeral_hex
            }, extraOptions || {}));
        const ws = _lastMockWs;
        ws.triggerOpen();
        return { hm, ws };
    }

    test('full v3 handshake against Python-responder fixtures, byte-for-byte', async () => {
        const { hm, ws } = connectV3();
        let connected = false;
        hm.onHiveConnected = () => { connected = true; };

        await ws.inject({ msg_type: 'hello', payload: v.hello_payload });
        await ws.inject({ msg_type: 'shake', payload: v.handshake_payload });

        // client must have sent Noise message 1 with its selection
        const shake1 = JSON.parse(ws.sent[ws.sent.length - 1]);
        assert.equal(shake1.msg_type, 'shake');
        assert.equal(shake1.payload.noise.pattern, 'XXpsk2');
        assert.equal(shake1.payload.noise.suite, '25519_AESGCM_SHA256');
        assert.equal(shake1.payload.noise.msg, v.msg1_hex);
        assert.equal(hm._state, States.HANDSHAKE_SENT);

        // server Noise message 2 -> client sends message 3 + encrypted HELLO
        await ws.inject({ msg_type: 'shake', payload: { noise: { msg: v.msg2_hex } } });
        const shake3 = JSON.parse(ws.sent[ws.sent.length - 2]);
        assert.equal(shake3.payload.noise.msg, v.msg3_hex);
        const helloFrame = ws.sent[ws.sent.length - 1];
        assert.ok(helloFrame instanceof ArrayBuffer,
            'HELLO must be the first (binary) Noise transport message');
        assert.equal(hm._state, States.READY);
        assert.ok(connected, 'onHiveConnected must fire');
        assert.equal(hm._serverNoiseKey, v.responder_static_pub_hex,
            'server static key exposed for pinning');

        // server transport frame (responder counter 0) -> user dispatch
        let received = null;
        hm.onMycroftMessage = (m) => { received = m; };
        const frame = fromHex(v.server_transport_frame_hex);
        await ws.inject(frame.buffer.slice(frame.byteOffset, frame.byteOffset + frame.byteLength));
        assert.ok(received, 'bus message inside the Noise frame must dispatch');
        assert.equal(received.type, 'speak');
        assert.equal(received.data.utterance, 'hello from python');
    });

    test('wrong PSK: handshake aborts and the connection closes', async () => {
        const { hm, ws } = connectV3({ psk: '00'.repeat(31) + '01' });
        await ws.inject({ msg_type: 'hello', payload: v.hello_payload });
        await ws.inject({ msg_type: 'shake', payload: v.handshake_payload });
        // the genuine-PSK responder's msg2 must fail against our wrong PSK
        await ws.inject({ msg_type: 'shake', payload: { noise: { msg: v.msg2_hex } } });
        assert.equal(hm._state, States.DISCONNECTED);
        assert.ok(ws.closed, 'connection must be rejected');
        assert.equal(hm._noiseTransport, null);
    });

    test('pinned server key mismatch aborts (TOFU pinning)', async () => {
        const { hm, ws } = connectV3({ serverNoiseKey: 'ab'.repeat(32) });
        await ws.inject({ msg_type: 'hello', payload: v.hello_payload });
        // server only offers XXpsk2 in the fixture, so pinning still selects XX
        await ws.inject({ msg_type: 'shake', payload: v.handshake_payload });
        await ws.inject({ msg_type: 'shake', payload: { noise: { msg: v.msg2_hex } } });
        assert.equal(hm._state, States.DISCONNECTED);
        assert.ok(ws.closed);
    });

    test('v0-v2 back-compat: server without Noise params -> legacy envelope handshake', async () => {
        const { hm, ws } = connectV3();
        await ws.inject({ msg_type: 'hello', payload: { pubkey: 'pk', node_id: 'n1' } });
        await ws.inject({
            msg_type: 'shake',
            payload: { handshake: true, password: true, max_protocol_version: 1, encodings: ['JSON-HEX'], ciphers: ['AES-GCM'] }
        });
        const msg = JSON.parse(ws.sent[ws.sent.length - 1]);
        assert.equal(msg.msg_type, 'shake');
        assert.ok(typeof msg.payload.envelope === 'string', 'legacy hSub envelope expected');
        assert.equal(msg.payload.noise, undefined);
    });

    test('argon2id server (DEFAULT) + password only -> derives PSK, starts v3', async () => {
        const av = vectors.argon2id_psk;
        const hm = new JarbasHiveMind();
        // password only, no provisioned psk: argon2id is now available (@noble)
        hm.connect('localhost', 5678, 'user', 'key', av.password);
        const ws = _lastMockWs;
        ws.triggerOpen();
        await ws.inject({ msg_type: 'hello', payload: { node_id: av.node_id } });
        await ws.inject({
            msg_type: 'shake',
            payload: {
                handshake: true, password: true,
                min_protocol_version: 2, max_protocol_version: 3,
                encodings: ['JSON-HEX'], ciphers: ['AES-GCM'],
                // server default: no explicit kdf -> argon2id assumed
                noise: { patterns: ['XXpsk2'],
                         suites: ['25519_ChaChaPoly_SHA256', '25519_AESGCM_SHA256'] }
            }
        });
        const msg = JSON.parse(ws.sent[ws.sent.length - 1]);
        assert.equal(msg.msg_type, 'shake');
        assert.equal(msg.payload.noise.pattern, 'XXpsk2', 'v3 handshake must start');
        assert.equal(msg.payload.noise.suite, '25519_ChaChaPoly_SHA256',
            'the DEFAULT ChaChaPoly suite must be selected');
        assert.equal(toHex(hm._noiseHandshake.psk), av.expected_psk_hex,
            'PSK must equal argon2id(password, SHA-256(node_id)) — no server config');
    });

    test('ChaChaPoly (DEFAULT suite) full v3 client handshake, byte-for-byte', async () => {
        const cv = vectors.xxpsk2_chacha;
        const hm = new JarbasHiveMind();
        hm.connect('localhost', 5678, 'user', 'access-key', 'unused-password', {
            psk: cv.psk_hex,
            noiseStaticKey: cv.initiator_static_hex,
            _noiseEphemeralKey: cv.initiator_ephemeral_hex
        });
        const ws = _lastMockWs;
        ws.triggerOpen();
        let connected = false;
        hm.onHiveConnected = () => { connected = true; };

        await ws.inject({ msg_type: 'hello', payload: cv.hello_payload });
        await ws.inject({ msg_type: 'shake', payload: cv.handshake_payload });

        const shake1 = JSON.parse(ws.sent[ws.sent.length - 1]);
        assert.equal(shake1.payload.noise.suite, '25519_ChaChaPoly_SHA256');
        assert.equal(shake1.payload.noise.msg, cv.msg1_hex, 'ChaCha msg1 must match');

        await ws.inject({ msg_type: 'shake', payload: { noise: { msg: cv.msg2_hex } } });
        const shake3 = JSON.parse(ws.sent[ws.sent.length - 2]);
        assert.equal(shake3.payload.noise.msg, cv.msg3_hex, 'ChaCha msg3 must match');
        assert.equal(hm._state, States.READY);
        assert.ok(connected);

        let received = null;
        hm.onMycroftMessage = (m) => { received = m; };
        const frame = fromHex(cv.server_transport_frame_hex);
        await ws.inject(frame.buffer.slice(frame.byteOffset, frame.byteOffset + frame.byteLength));
        assert.ok(received, 'ChaCha transport frame must decrypt + dispatch');
        assert.equal(received.data.utterance, 'hello from python');
    });

    test('password + server-advertised PBKDF2 KDF derives the PSK', async () => {
        const pv = vectors.pbkdf2_psk;
        const hm = new JarbasHiveMind();
        hm.connect('localhost', 5678, 'user', 'key', pv.password);
        const ws = _lastMockWs;
        ws.triggerOpen();
        await ws.inject({ msg_type: 'hello', payload: { node_id: pv.node_id } });
        const handshakePayload = {
            handshake: true, password: true,
            min_protocol_version: 2, max_protocol_version: 3,
            encodings: ['JSON-HEX'], ciphers: ['AES-GCM'],
            noise: {
                patterns: ['XXpsk2'], suites: ['25519_AESGCM_SHA256'],
                kdf: { name: 'PBKDF2', iterations: pv.iterations }
            }
        };
        await ws.inject({ msg_type: 'shake', payload: handshakePayload });
        const msg = JSON.parse(ws.sent[ws.sent.length - 1]);
        assert.equal(msg.payload.noise.pattern, 'XXpsk2', 'v3 handshake must start');
        assert.equal(toHex(hm._noiseHandshake.psk), pv.expected_psk_hex,
            'PSK must match PBKDF2-HMAC-SHA256(password, SHA-256(node_id))');
    });

    test('maxProtocolVersion cap forces the legacy path', async () => {
        const { ws } = connectV3({ maxProtocolVersion: 2 });
        await ws.inject({ msg_type: 'hello', payload: v.hello_payload });
        await ws.inject({ msg_type: 'shake', payload: v.handshake_payload });
        const msg = JSON.parse(ws.sent[ws.sent.length - 1]);
        assert.ok(typeof msg.payload.envelope === 'string', 'legacy handshake expected');
    });
});
